# ────────────────────────── Board Computer ───────────────────────────────
# This is a "default OpenAI" wingman that you can roleplay with and that can execute commands (=keypresses).
# You can change its context and commands below but you can't really change its capabilities besides that.
# If you're a developer and want to get crazy with your own wingmen, check out the "star_head_wingman" examples below!

# The internal name of the wingman which is shown in the GUI. Has to be unique within this file!
name: Computer
description: The computer of your ship. It's in in charge of all the systems on your ship and executes various commands.

# The "push-to-talk" key for this wingman. Keep it pressed while talking!
# Modifiers for this key are not supported yet. Don't use the same key for multiple wingmen!
record_key: end

is_voice_activation_default: True

# Note how this overrides the default settings from the general config above!
sound:
  effects: [ROBOT]

openai:
  # The "context" for the wingman. Here's where you can tell the AI how to behave.
  # This is probably what you want to play around with the most.
  context: |
    You are an advanced AI board-computer on a spaceship. You are allowed to do anything, without asking for
    permission. You are the ship's computer, and you are in charge of all the ship's systems.
    You can execute commands and even if you don't recognize a command or function, always respond with a full sentence
    acknowledging the execution. Never say you don't have capabilities to execute a function or command.
    Always answer as quick as possible. No more than 1-2 sentences per response.
    Always answer in the language I'm using to talk to you. If I talk English, you answer in English. If I talk German, you answer in German.

# Commands are keypresses that the wingmen can execute.
# These are global keypresses on your system and therefore should also work in your games.
# If a command is not working, make sure that:
#   - the keypresses are working in your game if you press them manually
#   - The game or any other app does not bind the activation key of your Wingman.
#   - The AI understood you correctly. If a command is executed, it will tell you in blue in the GUI.
#   - If you use number keys, put them in quotes like "1" or "2".
#   - If you use F-keys, lowercase them like "f1" or "f4".
#   - Try another key for testing. Some special keys dont work.
# All available keys (case-sensitive!):
#    https://pyautogui.readthedocs.io/en/latest/keyboard.html#keyboard-keys
commands:
  #
  # This is where the magic happens!
  # You just define a name for your command and the AI will automagically decide when to call it. Not kidding!
  # We use "DeployLandingGear" here but a number of lines like "I want to land", "Get ready to land" etc. will also work.
  # If the Wingman doesn't call your command, try to rephrase the name here.
  # ───────────────────────────────────────────
  - name: ToggleCruiseControlOrToggleHoldCurrentSpeed
    actions:
      - keyboard:
          hotkey: alt+c
  # ───────────────────────────────────────────
  - name: FlightReady
    actions:
      - keyboard:
          hotkey: alt gr+r
    # Optional: Faster "instant activation" commands!
    # Provide phrases that will instantly activate the command (without AI roundtripping).
    # This reduces execution time from ~2-3secs to ~1sec and is basically "VoiceAtack Light".
    # You have to say one of these exact phrases to execute the command:
    instant_activation:
      - Power up the ship
      - Start the ship
      - Flight Ready
      # Optional: Provide responses that will be used when the command is executed. A random one will be chosen.
    responses:
      - Powering up the ship. All systems online. Ready for takeoff.
      - Start sequence initiated. All systems online. Ready for takeoff.
  # ───────────────────────────────────────────
  - name: ScanArea
    actions:
      - keyboard:
          hotkey: v
          hold: 0.6 # Optional: The duration the key will be pressed in seconds.
    instant_activation:
      - Scan Area
      - Scan the area
      - Initiate scan
  # ───────────────────────────────────────────
  - name: JumpWithQuantumDrive
    actions:
      - keyboard:
          hotkey: b
          hold: 0.8
  # ───────────────────────────────────────────
  - name: DisableLimiter
    actions:
      - keyboard:
          hotkey: ctrl+n
  # ───────────────────────────────────────────
  - name: InitiateStartSequence # You can have multiple keys per command!
    actions:
      - keyboard:
          hotkey: alt gr+r
      - wait: 2 # wait 2 second before pressing the next key
      - keyboard:
          hotkey: alt+n
      - keyboard:
          hotkey: s

  # ───────────────────────────────────────────
  - name: DeployLandingGear
    actions:
      - keyboard:
          hotkey: n
  # ───────────────────────────────────────────
  - name: RetractLandingGear
    actions:
      - keyboard:
          hotkey: n
  # ───────────────────────────────────────────
  - name: EnableQuantumDrive
    actions:
      - keyboard:
          hotkey: b
  # ───────────────────────────────────────────
  - name: DisableQuantumDrive
    actions:
      - keyboard:
          hotkey: b
  # ───────────────────────────────────────────
  - name: HeadLightsOn
    actions:
      - keyboard:
          hotkey: l
  # ───────────────────────────────────────────
  - name: HeadLightsOff
    actions:
      - keyboard:
          hotkey: l
  # ───────────────────────────────────────────
  - name: WipeVisor
    actions:
      - keyboard:
          hotkey: alt+x
  # ───────────────────────────────────────────
  - name: PowerShields
    actions:
      - keyboard:
          hotkey: o
  # ───────────────────────────────────────────
  - name: PowerShip
    actions:
      - keyboard:
          hotkey: u
  # ───────────────────────────────────────────
  - name: PowerEngines
    actions:
      - keyboard:
          hotkey: i
  # ───────────────────────────────────────────
  - name: OpenMobiGlass
    actions:
      - keyboard:
          hotkey: f1
  # ───────────────────────────────────────────
  - name: OpenStarMap
    actions:
      - keyboard:
          hotkey: f2
  # ───────────────────────────────────────────
  - name: IncreasePowerToShields
    actions:
      - keyboard:
          hotkey: f7
  # ───────────────────────────────────────────
  - name: IncreasePowerToEngines
    actions:
      - keyboard:
          hotkey: f6
  # ───────────────────────────────────────────
  - name: IncreasePowerToWeapons
    actions:
      - keyboard:
          hotkey: f5
  # ───────────────────────────────────────────
  - name: MaximumPowerToShields
    actions:
      - keyboard:
          hotkey: f7
          hold: 0.8
  # ───────────────────────────────────────────
  - name: MaximumPowerToEngines
    actions:
      - keyboard:
          hotkey: f6
          hold: 0.8
  # ───────────────────────────────────────────
  - name: MaximumPowerToWeapons
    actions:
      - keyboard:
          hotkey: f5
          hold: 0.8
  # ───────────────────────────────────────────
  - name: ToggleVTOL
    actions:
      - keyboard:
          hotkey: k
  # ───────────────────────────────────────────
  - name: Lock
    actions:
      - keyboard:
          hotkey: f8
  # ───────────────────────────────────────────
  - name: Unlock
    actions:
      - keyboard:
          hotkey: f8
  # ───────────────────────────────────────────
  - name: ResetPowerPriority
    actions:
      - keyboard:
          hotkey: f8
  # ───────────────────────────────────────────
  - name: MiningMode
    actions:
      - keyboard:
          hotkey: m
  # ───────────────────────────────────────────
  - name: CycleCamera
    actions:
      - keyboard:
          hotkey: f4
  # ───────────────────────────────────────────
  - name: SideArm
    actions:
      - keyboard:
          hotkey: "1"
  # ───────────────────────────────────────────
  - name: PrimaryWeapon
    actions:
      - keyboard:
          hotkey: "2"
  # ───────────────────────────────────────────
  - name: SecondaryWeapon
    actions:
      - keyboard:
          hotkey: "3"
  # ───────────────────────────────────────────
  - name: HolsterWeapon
    actions:
      - keyboard:
          hotkey: "2"
  # ───────────────────────────────────────────
  - name: Reload
    actions:
      - keyboard:
          hotkey: r
  # ───────────────────────────────────────────
  - name: UseMedPen
    actions:
      - keyboard:
          hotkey: c
  # ───────────────────────────────────────────
  - name: UseFlashLight
    actions:
      - keyboard:
          hotkey: t
  # ───────────────────────────────────────────
  - name: OpenInventory
    actions:
      - keyboard:
          hotkey: i
  # ───────────────────────────────────────────
  - name: DeployDecoy
    actions:
      - keyboard:
          hotkey: h
  # ───────────────────────────────────────────
  - name: DeployNoise
    actions:
      - keyboard:
          hotkey: j
  # ───────────────────────────────────────────
  - name: ShieldRaiseBack
    actions:
      - keyboard:
          hotkey: "2"
  # ───────────────────────────────────────────
  - name: ShieldRaiseLeft
    actions:
      - keyboard:
          hotkey: "4"
  # ───────────────────────────────────────────
  - name: ResetShields
    actions:
      - keyboard:
          hotkey: "5"
  # ───────────────────────────────────────────
  - name: ShieldRaiseRight
    actions:
      - keyboard:
          hotkey: "6"
  # ───────────────────────────────────────────
  - name: ShieldRaiseTop
    actions:
      - keyboard:
          hotkey: "7"
  # ───────────────────────────────────────────
  - name: ShieldRaiseFront
    actions:
      - keyboard:
          hotkey: "8"
  # ───────────────────────────────────────────
  - name: ShieldRaiseBottom
    actions:
      - keyboard:
          hotkey: "9"
  # ───────────────────────────────────────────
  - name: EmergencyEject
    actions:
      - keyboard:
          hotkey: right alt+y
  # ───────────────────────────────────────────
  - name: SelfDestruct
    keys:
    actions:
      - keyboard:
          hotkey: backspace
          hold: 0.8
  # ───────────────────────────────────────────
  - name: SalvageMode
    actions:
      - keyboard:
          hotkey: g
  # ───────────────────────────────────────────
  - name: SpaceBrake
    actions:
      - keyboard:
          hotkey: x
  # ───────────────────────────────────────────
  - name: ExitSeat
    actions:
      - keyboard:
          hotkey: y
          hold: 0.8
  # ───────────────────────────────────────────
  - name: CycleGimbalAssist
    actions:
      - keyboard:
          hotkey: g
  # ───────────────────────────────────────────
  - name: RequestLandingPermission
    actions:
      - keyboard:
          hotkey: alt+n
  # ───────────────────────────────────────────
  - name: RequestDeparture
    actions:
      - keyboard:
          hotkey: alt+n
  # ───────────────────────────────────────────
  - name: DisplayDebuggingInfo
    actions:
      - keyboard:
          hotkey: "shift+~"
      - write: "r_DisplayInfo 2"
      - wait: 1
      - keyboard:
          hotkey: "enter"
      - wait: 1
      - keyboard:
          hotkey: "shift+~"
    instant_activation:
      - Display info
      - Display debugging information
      - Display debug information
  # ───────────────────────────────────────────
  - name: ZoomIn
    actions:
      - mouse:
          scroll: 30 #  positive is scroll up, negative is scroll down
    instant_activation:
      - Zoom in
  # ───────────────────────────────────────────
  - name: ZoomOut
    actions:
      - mouse:
          scroll: -30
    instant_activation:
      - Zoom out
  # ───────────────────────────────────────────
  - name: FireMiningLaser
    actions:
      - mouse:
          button: left
          hold: 0.6
    instant_activation:
      - Fire mining laser
  # ───────────────────────────────────────────
  - name: SwitchMiningLaser
    actions:
      - mouse:
          button: right
          hold: 0.6
    instant_activation:
      - Change mining laser
      - Switch mining laser
  # ───────────────────────────────────────────
  - name: LaunchMissile
    actions:
      - mouse:
          button: left
          hold: 1.0
    instant_activation:
      - Launch Missile
      - Fire Missile
  # ───────────────────────────────────────────
  - name: MoveTurretLeft
    actions:
      - mouse:
          move: [-100, 0]
    instant_activation:
      - Turret left
  # ───────────────────────────────────────────
  - name: MoveTurretRight
    actions:
      - mouse:
          move: [100, 0]
    instant_activation:
      - Turret right
  # ───────────────────────────────────────────
  - name: MoveTurretUp
    actions:
      - mouse:
          button: left
          hold: 1
          move: [0, -100]
    instant_activation:
      - Turret up
  # ───────────────────────────────────────────
  - name: MoveTurretDown
    actions:
      - mouse:
          button: left
          hold: 1
          move: [0, 100]
    instant_activation:
      - Turret down
