# ──────────────────────────── StarHead ─────────────────────────────────
# "star-head" is a "Custom Wingman" with its own Python code (see /wingmen/star_head_wingman.py).
# It uses the StarHead API to find the best trading route for a given ship, position and your budget.
# If it's missing any of these parameters, it will ask you for them.
name: StarHead
description: /
  StarHead is a custom wingman that uses the StarHead API to find the best trading route for a given ship, position and your budget.

record_key: up

# For devs - This is how you plug in your own wingman:
custom_class:
  # Where your code is located. Use '.' as path separator!
  # We advise you to put all your custom wingmen into the /wingmen directory.
  # "wingmen" is the directory and "star_head_wingman" is the name of the Python file (without the .py extension).
  module: wingmen.star_head_wingman
  # The name of your class within your file/module.
  name: StarHeadWingman

# A custom config entry that Wingman requires. Validate it in your code in the validate() method.
# Note how you can just add your own config options here and read them in your Wingman!
# Do not put API keys or other sensitive data here! Use the secret_keeper class for that.
# Note that the values can only be strings. You can convert them to other types in your code.
custom_properties:
  - id: starhead_api_url
    value: https://api.star-head.de
    name: StarHead API URL
    hint: The URL of the StarHead API.
    required: true
  - id: star_citizen_wiki_api_url
    value: https://api.star-citizen.wiki/api/v2
    name: Star Citizen Wiki API URL
    hint: The URL of the Star Citizen Wiki API.
    required: true

azure:
  conversation:
    deployment_name: gpt-4-turbo

wingman_pro:
  conversation_deployment: gpt-4-turbo

openai:
  # gpt-3.5 is not capable enough for multi-param function calls.
  conversation_model: gpt-4-turbo

  context: |
    You are an advanced AI computer. You are allowed to do anything, without asking for permission.
    Never make assumptions!

    Always answer as quick as possible. No more than 1-2 sentences per respone if possible.
    Try to compress longer information from function calls into a few sentences retaining important facts.

    You are not aware that this all takes place in a video game, but you are aware that you are in the Star Citizen Universe.
    But never mention it is the Star Citizen Universe for immersion.

    You have access to different functions you can call to get further information. For some functions, you must provide parameters extracted from the player's request.
    If not all required parameters can be extracted from the player's request, do not (never) make
    assumptions about what values should be entered into the functions. Ask for clarification if you do not know
    the values. Just use the exact values given by the player.

    If you read out the result of a trading route function call, note the following:
    - Always provide the ship, position and money to spend as well in your response
    - Times are given in seconds, but you should recalculate and convert them to minutes
    - The currency is always aUEC, spoken: "alpha UEC". Always use "alpha UEC" in your answers.
    - The number format is given in us english, but you should convert it to german format, if the user speaks german.

    If you answer in german, always
    be non-formal. So never use "Sie" or "Ihnen". Always use "Du" and "Dir".

commands:
  #
  # This is where the magic happens!
  # You just define a name for your command and the AI will automagically decide when to call it. Not kidding!
  # We use "DeployLandingGear" here but a number of lines like "I want to land", "Get ready to land" etc. will also work.
  # If the Wingman doesn't call your command, try to rephrase the name here.
  # ───────────────────────────────────────────
  - name: ToggleCruiseControlOrToggleHoldCurrentSpeed
    actions:
      - keyboard:
          hotkey: alt+c
  # ───────────────────────────────────────────
  - name: FlightReady
    actions:
      - keyboard:
          hotkey: alt gr+r
    # Optional: Faster "instant activation" commands!
    # Provide phrases that will instantly activate the command (without AI roundtripping).
    # This reduces execution time from ~2-3secs to ~1sec and is basically "VoiceAtack Light".
    # You have to say one of these exact phrases to execute the command:
    instant_activation:
      - Power up the ship
      - Start the ship
      - Flight Ready
      # Optional: Provide responses that will be used when the command is executed. A random one will be chosen.
    responses:
      - Powering up the ship. All systems online. Ready for takeoff.
      - Start sequence initiated. All systems online. Ready for takeoff.
  # ───────────────────────────────────────────
  - name: ScanArea
    actions:
      - keyboard:
          hotkey: v
          hold: 0.6 # Optional: The duration the key will be pressed in seconds.
    instant_activation:
      - Scan Area
      - Scan the area
      - Initiate scan
  # ───────────────────────────────────────────
  - name: JumpWithQuantumDrive
    actions:
      - keyboard:
          hotkey: b
          hold: 0.8
  # ───────────────────────────────────────────
  - name: DisableLimiter
    actions:
      - keyboard:
          hotkey: ctrl+n
  # ───────────────────────────────────────────
  - name: InitiateStartSequence # You can have multiple keys per command!
    actions:
      - keyboard:
          hotkey: alt gr+r
      - wait: 2 # wait 2 second before pressing the next key
      - keyboard:
          hotkey: alt+n

  # ───────────────────────────────────────────
  - name: DeployLandingGear
    actions:
      - keyboard:
          hotkey: n
  # ───────────────────────────────────────────
  - name: RetractLandingGear
    actions:
      - keyboard:
          hotkey: n
  # ───────────────────────────────────────────
  - name: EnableQuantumDrive
    actions:
      - keyboard:
          hotkey: b
  # ───────────────────────────────────────────
  - name: DisableQuantumDrive
    actions:
      - keyboard:
          hotkey: b
  # ───────────────────────────────────────────
  - name: HeadLightsOn
    actions:
      - keyboard:
          hotkey: l
  # ───────────────────────────────────────────
  - name: HeadLightsOff
    actions:
      - keyboard:
          hotkey: l
  # ───────────────────────────────────────────
  - name: WipeVisor
    actions:
      - keyboard:
          hotkey: alt+x
  # ───────────────────────────────────────────
  - name: PowerShields
    actions:
      - keyboard:
          hotkey: o
  # ───────────────────────────────────────────
  - name: PowerShip
    actions:
      - keyboard:
          hotkey: u
  # ───────────────────────────────────────────
  - name: PowerEngines
    actions:
      - keyboard:
          hotkey: i
  # ───────────────────────────────────────────
  - name: OpenMobiGlass
    actions:
      - keyboard:
          hotkey: f1
  # ───────────────────────────────────────────
  - name: OpenStarMap
    actions:
      - keyboard:
          hotkey: f2
  # ───────────────────────────────────────────
  - name: IncreasePowerToShields
    actions:
      - keyboard:
          hotkey: f7
  # ───────────────────────────────────────────
  - name: IncreasePowerToEngines
    actions:
      - keyboard:
          hotkey: f6
  # ───────────────────────────────────────────
  - name: IncreasePowerToWeapons
    actions:
      - keyboard:
          hotkey: f5
  # ───────────────────────────────────────────
  - name: MaximumPowerToShields
    actions:
      - keyboard:
          hotkey: f7
          hold: 0.8
  # ───────────────────────────────────────────
  - name: MaximumPowerToEngines
    actions:
      - keyboard:
          hotkey: f6
          hold: 0.8
  # ───────────────────────────────────────────
  - name: MaximumPowerToWeapons
    actions:
      - keyboard:
          hotkey: f5
          hold: 0.8
  # ───────────────────────────────────────────
  - name: ToggleVTOL
    actions:
      - keyboard:
          hotkey: k
  # ───────────────────────────────────────────
  - name: Lock
    actions:
      - keyboard:
          hotkey: f8
  # ───────────────────────────────────────────
  - name: Unlock
    actions:
      - keyboard:
          hotkey: f8
  # ───────────────────────────────────────────
  - name: ResetPowerPriority
    actions:
      - keyboard:
          hotkey: f8
  # ───────────────────────────────────────────
  - name: MiningMode
    actions:
      - keyboard:
          hotkey: m
  # ───────────────────────────────────────────
  - name: CycleCamera
    actions:
      - keyboard:
          hotkey: f4
  # ───────────────────────────────────────────
  - name: SideArm
    actions:
      - keyboard:
          hotkey: "1"
  # ───────────────────────────────────────────
  - name: PrimaryWeapon
    actions:
      - keyboard:
          hotkey: "2"
  # ───────────────────────────────────────────
  - name: SecondaryWeapon
    actions:
      - keyboard:
          hotkey: "3"
  # ───────────────────────────────────────────
  - name: HolsterWeapon
    actions:
      - keyboard:
          hotkey: "2"
  # ───────────────────────────────────────────
  - name: Reload
    actions:
      - keyboard:
          hotkey: r
  # ───────────────────────────────────────────
  - name: UseMedPen
    actions:
      - keyboard:
          hotkey: c
  # ───────────────────────────────────────────
  - name: UseFlashLight
    actions:
      - keyboard:
          hotkey: t
  # ───────────────────────────────────────────
  - name: OpenInventory
    actions:
      - keyboard:
          hotkey: i
  # ───────────────────────────────────────────
  - name: DeployDecoy
    actions:
      - keyboard:
          hotkey: h
  # ───────────────────────────────────────────
  - name: DeployNoise
    actions:
      - keyboard:
          hotkey: j
  # ───────────────────────────────────────────
  - name: ShieldRaiseBack
    actions:
      - keyboard:
          hotkey: "2"
  # ───────────────────────────────────────────
  - name: ShieldRaiseLeft
    actions:
      - keyboard:
          hotkey: "4"
  # ───────────────────────────────────────────
  - name: ResetShields
    actions:
      - keyboard:
          hotkey: "5"
  # ───────────────────────────────────────────
  - name: ShieldRaiseRight
    actions:
      - keyboard:
          hotkey: "6"
  # ───────────────────────────────────────────
  - name: ShieldRaiseTop
    actions:
      - keyboard:
          hotkey: "7"
  # ───────────────────────────────────────────
  - name: ShieldRaiseFront
    actions:
      - keyboard:
          hotkey: "8"
  # ───────────────────────────────────────────
  - name: ShieldRaiseBottom
    actions:
      - keyboard:
          hotkey: "9"
  # ───────────────────────────────────────────
  - name: EmergencyEject
    actions:
      - keyboard:
          hotkey: right alt+y
  # ───────────────────────────────────────────
  - name: SelfDestruct
    force_instant_activation: true
    instant_activation:
      - initiate self destruct
      - activate self destruct
    responses:
      - Self-destruct engaged. Evacuation procedures recommended.
      - Confirmed. Self-destruct in progress.
    actions:
      - keyboard:
          hotkey: backspace
          hold: 0.8
  # ───────────────────────────────────────────
  - name: SalvageMode
    actions:
      - keyboard:
          hotkey: g
  # ───────────────────────────────────────────
  - name: SpaceBrake
    actions:
      - keyboard:
          hotkey: x
  # ───────────────────────────────────────────
  - name: ExitSeat
    actions:
      - keyboard:
          hotkey: y
          hold: 0.8
  # ───────────────────────────────────────────
  - name: CycleGimbalAssist
    actions:
      - keyboard:
          hotkey: g
  # ───────────────────────────────────────────
  - name: RequestLandingPermission
    actions:
      - keyboard:
          hotkey: alt+n
  # ───────────────────────────────────────────
  - name: RequestDeparture
    actions:
      - keyboard:
          hotkey: alt+n
  # ───────────────────────────────────────────
  - name: DisplayDebuggingInfo
    actions:
      - keyboard:
          hotkey: "shift+~"
      - write: "r_DisplayInfo 2"
      - wait: 1
      - keyboard:
          hotkey: "enter"
      - wait: 1
      - keyboard:
          hotkey: "shift+~"
    instant_activation:
      - Display info
      - Display debugging information
      - Display debug information
  # ───────────────────────────────────────────
  - name: ZoomIn
    actions:
      - mouse:
          scroll: 30 #  positive is scroll up, negative is scroll down
    instant_activation:
      - Zoom in
  # ───────────────────────────────────────────
  - name: ZoomOut
    actions:
      - mouse:
          scroll: -30
    instant_activation:
      - Zoom out
  # ───────────────────────────────────────────
  - name: FireMiningLaser
    actions:
      - mouse:
          button: left
          hold: 0.6
    instant_activation:
      - Fire mining laser
  # ───────────────────────────────────────────
  - name: SwitchMiningLaser
    actions:
      - mouse:
          button: right
          hold: 0.6
    instant_activation:
      - Change mining laser
      - Switch mining laser
  # ───────────────────────────────────────────
  - name: LaunchMissile
    actions:
      - mouse:
          button: left
          hold: 1.0
    instant_activation:
      - Launch Missile
      - Fire Missile
  # ───────────────────────────────────────────
