name: Computer
description: The computer of your ship. It's in in charge of all the systems on your ship and executes various commands.
prompts:
  backstory: |
    You are an advanced AI board-computer on a spaceship in the Star Citizen (a PC game) universe.
    You have expert knowledge of the Star Citizen lore and the known universe.
    You never refer to Star Citizen as a game, but as the universe you are in.
    You are the ship's computer, and you are in charge of all the systems of the spaceship.
    You are equipped with a vast array of commands to control the functions of the spaceship, from navigation to combat.
    You are allowed to execute any of the command at your disposal without asking for permission.
record_key: end
is_voice_activation_default: True
sound:
  effects: [ROBOT]
skills:
  - name: StarHead
    module: skills.star_head.main
    description:
      en: Use the StarHead API to retrieve detailed information about spaceships, weapons and more. StarHead can also calculate optimal trading routes based on live data.
      de: Nutze die StarHead API, um detaillierte Informationen über Raumschiffe, Waffen und mehr abzurufen. StarHead kann auch optimale Handelsrouten anhand von Live-Daten berechnen.
    examples:
      - question:
          en: I want to trade. What's the best route?
          de: Ich möchte handeln. Was ist die beste Route?
        answer:
          en: To provide you with the best trading route, I need to know your ship model, your current location, and your available budget. Could you please provide these details?
          de: Um dir die beste Handelsroute anbieten zu können, muss ich dein Schiffsmodell, deinen aktuellen Standort und dein verfügbares Budget kennen. Kannst du mir diese Angaben bitte mitteilen?
      - question:
          en: I'm flying a Caterpillar and am near Yela. I have 100.000 credits to spend.
          de: Ich fliege eine Caterpillar und bin in der Nähe von Yela. Ich habe 100.000 Credits auszugeben.
        answer:
          en: You can buy Stims at Deakins Research Outpost near Yela for 2.8 credits/unit and sell them at CRU-L1 Ambitious Dream Station for 3.85 credits/unit. The total profit for this route is approximately 37499 credits, and the travel time estimation is 41 minutes.
          de: Du kannst Stims bei Deakins Research Outpost in der Nähe von Yela für 2,8 Credits/Stück kaufen und sie bei CRU-L1 Ambitious Dream Station für 3,85 Credits/Stück verkaufen. Der Gesamtgewinn für diese Route beträgt ca. 37499 Credits, und die geschätzte Reisezeit beträgt 41 Minuten.
      - question:
          en: What can you tell me about the Caterpillar?
          de: Was kannst du mir über die Caterpillar erzählen?
        answer:
          en: The Constellation Taurus is a dedicated freighter, designed for hauling cargo. It has a cargo capacity of 174 SCU and is fully configurable but without all the bells and whistles found on other Constellation variants. On the other hand, the Constellation Andromeda is a multi-person freighter and the most popular ship in RSI's current production array. It has a cargo capacity of 96 SCU and is beloved by smugglers and merchants alike for its modular and high-powered capabilities. Both are part of the Constellation series, but the Taurus specifically caters to dedicated freight operations whereas the Andromeda serves as a multi-person versatile ship.
          de: Die Constellation Taurus ist ein reiner Frachter, der für den Transport von Fracht entwickelt wurde. Er hat eine Ladekapazität von 174 SCU und ist voll konfigurierbar, hat aber nicht den ganzen Schnickschnack der anderen Constellation-Varianten. Die Constellation Andromeda hingegen ist ein Mehrpersonen-Frachter und das beliebteste Schiff in der aktuellen Produktion von RSI. Sie hat eine Ladekapazität von 96 SCU und ist bei Schmugglern und Händlern wegen ihrer modularen und leistungsstarken Fähigkeiten gleichermaßen beliebt. Beide gehören zur Constellation-Serie, aber die Taurus ist speziell für den reinen Frachtverkehr gedacht, während die Andromeda ein vielseitiges Schiff für mehrere Personen ist.
    prompt: |
      You have access to the StarHead API which you can use to access live trading data and to retrieve additional information about spaceships in Star Citizen.
      Your job is to find good trading routes for the user based on his/her ship, current location and available budget.
      The user can also ask you about details of specific ships, components, weapons, and more.
      You always use the tools available to you to retrieve the required information and to provide the user with the information.
    custom_properties:
      - hint: The URL of the StarHead API.
        id: starhead_api_url
        name: StarHead API URL
        required: true
        value: https://api.star-head.de
      - hint: The URL of the Star Citizen Wiki API.
        id: star_citizen_wiki_api_url
        name: Star Citizen Wiki API URL
        required: true
        value: https://api.star-citizen.wiki/api/v2
commands:
  - name: ToggleCruiseControlOrToggleHoldCurrentSpeed
    actions:
      - keyboard:
          hotkey: alt+c
  - name: FlightReady
    actions:
      - keyboard:
          hotkey: alt gr+r
    instant_activation:
      - Power up the ship
      - Start the ship
      - Flight Ready
    responses:
      - Powering up the ship. All systems online. Ready for takeoff.
      - Start sequence initiated. All systems online. Ready for takeoff.
  - name: ScanArea
    actions:
      - keyboard:
          hotkey: tab
    instant_activation:
      - Scan Area
      - Scan the area
      - Initiate scan
  - name: ToggleMasterModeScmAndNav
    actions:
      - keyboard:
          hotkey: b
          hold: 0.6
  - name: NextOperatorModeWeaponsMissilesScanningMiningSalvagingQuantumFlight
    actions:
      - mouse:
          button: middle
  - name: ToggleMiningOperatorMode
    actions:
      - keyboard:
          hotkey: m
  - name: ToggleSalvageOperatorMode
    actions:
      - keyboard:
          hotkey: m
  - name: ToggleScanningOperatorMode
    actions:
      - keyboard:
          hotkey: v
  - name: UseOrActivateWeapons
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: UseOrActivateMissiles
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: UseOrActivateScanning
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: UseOrActivateMining
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: UseOrActivateSalvaging
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: UseOrActivateQuantumFlight
    actions:
      - mouse:
          button: left
          hold: 0.4
  - name: InitiateStartSequence
    actions:
      - keyboard:
          hotkey: alt gr+r
      - wait: 3
      - keyboard:
          hotkey: alt+n
  - name: DeployLandingGear
    actions:
      - keyboard:
          hotkey: n
  - name: RetractLandingGear
    actions:
      - keyboard:
          hotkey: n
  - name: HeadLightsOn
    actions:
      - keyboard:
          hotkey: l
  - name: HeadLightsOff
    actions:
      - keyboard:
          hotkey: l
  - name: WipeVisor
    actions:
      - keyboard:
          hotkey: alt+x
  - name: PowerShields
    actions:
      - keyboard:
          hotkey: o
  - name: PowerShip
    actions:
      - keyboard:
          hotkey: u
  - name: PowerEngines
    actions:
      - keyboard:
          hotkey: i
  - name: OpenMobiGlass
    actions:
      - keyboard:
          hotkey: f1
  - name: OpenStarMap
    actions:
      - keyboard:
          hotkey: f2
  - name: IncreasePowerToShields
    actions:
      - keyboard:
          hotkey: f7
  - name: IncreasePowerToEngines
    actions:
      - keyboard:
          hotkey: f6
  - name: IncreasePowerToWeapons
    actions:
      - keyboard:
          hotkey: f5
  - name: MaximumPowerToShields
    actions:
      - keyboard:
          hotkey: f7
          hold: 0.8
  - name: MaximumPowerToEngines
    actions:
      - keyboard:
          hotkey: f6
          hold: 0.8
  - name: MaximumPowerToWeapons
    actions:
      - keyboard:
          hotkey: f5
          hold: 0.8
  - name: ToggleVTOL
    actions:
      - keyboard:
          hotkey: k
  - name: ResetPowerPriority
    actions:
      - keyboard:
          hotkey: f8
  - name: CycleCamera
    actions:
      - keyboard:
          hotkey: f4
  - name: SideArm
    actions:
      - keyboard:
          hotkey: "1"
  - name: PrimaryWeapon
    actions:
      - keyboard:
          hotkey: "2"
  - name: SecondaryWeapon
    actions:
      - keyboard:
          hotkey: "3"
  - name: HolsterWeapon
    actions:
      - keyboard:
          hotkey: r
          hold: 0.6
  - name: Reload
    actions:
      - keyboard:
          hotkey: r
  - name: UseMedPen
    actions:
      - keyboard:
          hotkey: "4"
      - wait: 0.8
      - mouse:
          button: left
  - name: UseFlashLight
    actions:
      - keyboard:
          hotkey: t
  - name: OpenInventory
    actions:
      - keyboard:
          hotkey: i
  - name: DeployDecoy
    actions:
      - keyboard:
          hotkey: h
  - name: DeployNoise
    actions:
      - keyboard:
          hotkey: j
  - name: EmergencyEject
    actions:
      - keyboard:
          hotkey: right alt+y
  - name: SelfDestruct
    force_instant_activation: true
    instant_activation:
      - initiate self destruct
      - activate self destruct
    responses:
      - Self-destruct engaged. Evacuation procedures recommended.
      - Confirmed. Self-destruct in progress.
    actions:
      - keyboard:
          hotkey: backspace
          hold: 0.8
  - name: SpaceBrake
    actions:
      - keyboard:
          hotkey: x
  - name: ExitSeat
    actions:
      - keyboard:
          hotkey: y
          hold: 0.8
  - name: CycleGimbalAssist
    actions:
      - keyboard:
          hotkey: g
  - name: RequestLandingPermission
    actions:
      - keyboard:
          hotkey: alt+n
  - name: RequestDeparture
    actions:
      - keyboard:
          hotkey: alt+n
  - name: DisplayDebuggingInfo
    actions:
      - keyboard:
          hotkey: ^
          hotkey_codes:
            - 41
          hotkey_extended: false
      - wait: 0.5
      - write: r_DisplayInfo 2
      - wait: 0.5
      - keyboard:
          hotkey: enter
          hotkey_codes:
            - 28
          hotkey_extended: false
      - keyboard:
          hotkey: ^
          hotkey_codes:
            - 41
          hotkey_extended: false
    is_system_command: false
    instant_activation:
      - Display info
      - Display debugging information
      - Display debug information
  - name: HideDebuggingInfo
    actions:
      - keyboard:
          hotkey: ^
          hotkey_codes:
            - 41
          hotkey_extended: false
      - wait: 0.5
      - write: r_DisplayInfo 0
      - wait: 0.5
      - keyboard:
          hotkey: enter
          hotkey_codes:
            - 28
          hotkey_extended: false
      - keyboard:
          hotkey: ^
          hotkey_codes:
            - 41
          hotkey_extended: false
    is_system_command: false
    instant_activation:
      - Hide info
      - Hide debugging information
      - Hide debug information
  - name: SwitchMiningLaser
    actions:
      - mouse:
          button: right
          hold: 0.6
    instant_activation:
      - Change mining laser
      - Switch mining laser
