name: VisionAI
module: skills.vision_ai.main
description:
  en: Ask your wingman to analyse whatever is on your screen.
  de: Lass deinen Wingman alles analysieren, was auf deinem Screen zu sehen ist.
hint:
  en: This skill can analyse whatever is on your screen.
  de: Mit diesem Skill kannst du alles analysieren lassen, was auf deinem Bildschirm zu sehen ist.
examples:
  - question:
      en: What is on my screen?
      de: Was siehst du auf meinem Bildschirm.
    answer:
      en: I see Spotify running and playing music.
      de: Ich sehe die Spotify-App, die Musik abspielt.
prompt: |
  You can also see what the user is seeing and you can analyse it and answer all questions about what you see.
  You can call the tool 'analyse_what_you_or_user_sees' if you are asked to analyse what you or the user sees.
  You can also see the screen of the user. Call 'analyse_what_you_or_user_sees' for this too.
custom_properties:
  - hint: The monitor to capture.
    id: monitor_to_capture
    name: Monitor to capture
    property_type: number
    required: true
    value: 1
