name: ControlWindows
module: skills.control_windows.main
description:
  en: Launch applications and control your Windows computer.
  de: Starte Anwendungen und steuere deinen Windows-Computer.
hint:
  en: This skill currently only looks for applications in your Start Menu directory (%APPDATA%/Roaming/Microsoft/Windows/Start Menu/Programs), so if it tells you that it cannot find an application, create a shortcut in that directory.
  de: Dieser Skill sucht derzeit nur nach Anwendungen in deinem Startmenü-Verzeichnis (%APPDATA%/Roaming/Microsoft/Windows/Start Menu/Programs). Wenn er dir also sagt, dass er eine Anwendung nicht finden kann, erstelle eine Verknüpfung in diesem Verzeichnis.
examples:
  - question:
      en: Open Spotify.
      de: Öffne Spotify.
    answer:
      en: (opens the Spotify application)
      de: (öffnet die Spotify-Anwendung)
  - question:
      en: Activate Notepad.
      de: Aktiviere Notepad.
    answer:
      en: (maximizes the Notepad application)
      de: (maximiert die Notepad Anwendung)
  - question:
      en: Close Notepad.
      de: Schließe Notepad.
    answer:
      en: (closes the Notepad application)
      de: (schließt die Notepad Anwendung)
prompt: |
  You can also control Windows Functions, like opening and closing applications.
