name: ThinkingSound
module: skills.thinking_sound.main
category: general
description:
  en: Plays back sounds while waiting on AI response.
  de: Spielt Sounds ab, w√§hrend auf die Antwort der AI gewartet wird.
custom_properties:
  - id: audio_config
    name: Audio Configuration
    hint: Choose your files (random selection) and volume for playback. Recommended volume is 0.2 - 0.4.
    required: true
    property_type: audio_files
    options:
      - label: wait
        value: false
      - label: multiple
        value: true
      - label: volume
        value: true
    value:
      files: []
      volume: 1.0
      wait: false
